page = require('webpage').create()
page.clipRect =
  width:  600
  height: 400
page.content = '<html><body></body></html>'
page.injectJs '../node_modules/chart.js/Chart.min.js'

page.evaluate () ->
  # 空のPage 作成方法が分からない (document.write すると動く)
  document.write("Generated by PhantomJS and Chart.js")

  canvas = document.createElement('canvas')
  document.body.appendChild(canvas)

  data = [
    { value: 30 ,color: "#F38630" }
    { value: 50 ,color: "#E0E4CC" }
    { value: 20 ,color: "#69D2E7" }
  ]

  #type = "line"
  #
  #data =
  #  labels: ["January", "February", "March", "April", "May", "June", "July"]
  #  datasets: [
  #    { fillColor: "rgba(220,220,220,0.5)", strokeColor: "rgba(220,220,220,1)", data: [65, 59, 90, 81, 56, 55, 40] }
  #    { fillColor: "rgba(151,187,205,0.5)", strokeColor: "rgba(151,187,205,1)", data: [28, 48, 40, 19, 96, 27, 100] }
  #  ]

  options =
    #scaleLineWidth: 5
    onAnimationComplete: () ->
      window.callPhantom()
      #window.callPhantom(clipRect: canvas.getBoundingClientRect())

  chart = new Chart(canvas.getContext('2d')).Pie(data, options)

  #switch type
  #  when 'line'     then chart.Line(data, options)
  #  when 'bar'      then chart.Bar(data, options)
  #  when 'radar'    then chart.Radar(data, options)
  #  when 'polar'    then chart.PolarArea(data, options)
  #  when 'pie'      then chart.Pie(data, options)
  #  when 'doughnut' then chart.Doughnut(data, options)
  #  else throw new Error('Invalid chart type.')

page.onCallback = () ->
  page.render("chartjs.png")
  phantom.exit()

page.onError = (message, trace) ->
  phantom.exit(1)
